<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;

class PlaceholderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        if(!Schema::hasTable('placeholders')){
            DB::unprepared(Storage::get('placeholders.sql'));
        }
        

        //code for creating the dump

        // Schema::create('placeholders', function ($table) {
        //     $table->increments('id');
        //     $table->text('type');
        //     $table->text('value');
        // });

        // for ($i = 0; $i < 15; $i++) {
        //     $offset = $i * 100;
        //     $dataset = file_get_contents("https://datasets-server.huggingface.co/rows?dataset=rajuptvs%2Fecommerce_products_clip&config=default&split=train&offset=" . $offset . '&limit=100');
        //     $dataset = json_decode($dataset);

        //     foreach ($dataset->rows as $row) {
        //         $image_path = 'placeholders/' . uniqid() . '.jpg';
        //         Storage::disk('public')->put($image_path, file_get_contents($row->row->image->src));
        //         DB::table('placeholders')->insert([
        //             'type' => 'name',
        //             'value' => $row->row->Product_name
        //         ]);
        //         DB::table('placeholders')->insert([
        //             'type' => 'description',
        //             'value' => $row->row->Description
        //         ]);
        //         DB::table('placeholders')->insert([
        //             'type' => 'image',
        //             'value' => $image_path
        //         ]);
        //     }
        // }



        // $categories = json_decode('{"categories": [
        //     "Womens Clothing",
        //     "Mens Clothing",
        //     "Childrens Clothing",
        //     "Shoes",
        //     "Bags",
        //     "Accessories",
        //     "Beauty",
        //     "Jewelry",
        //     "Watches",
        //     "Home Decor",
        //     "Furniture",
        //     "Kitchenware",
        //     "Bedding",
        //     "Bath",
        //     "Electronics",
        //     "Mobile Phones",
        //     "Computers",
        //     "Laptops",
        //     "Tablets",
        //     "Cameras",
        //     "Audio & Video",
        //     "Smart Home",
        //     "Gaming",
        //     "Books",
        //     "Movies",
        //     "Music",
        //     "Toys",
        //     "Games",
        //     "Sports",
        //     "Fitness",
        //     "Outdoor",
        //     "Hobbies",
        //     "Crafts",
        //     "Pet Supplies",
        //     "Stationery",
        //     "Party Supplies",
        //     "Food & Beverages",
        //     "Groceries",
        //     "Candy & Snacks",
        //     "Bakery",
        //     "Beverages",
        //     "Health & Wellness",
        //     "Vitamins & Supplements",
        //     "Personal Care",
        //     "Medicine",
        //     "Fitness Equipment",
        //     "Home Improvement",
        //     "Tools",
        //     "Hardware",
        //     "Appliances",
        //     "Lighting",
        //     "Garden",
        //     "Patio",
        //     "Automotive",
        //     "Car Accessories",
        //     "Motorcycle Accessories",
        //     "Outdoor Equipment",
        //     "Travel",
        //     "Luggage",
        //     "Travel Accessories",
        //     "Clothing",
        //     "Electronics",
        //     "Home",
        //     "Garden & Tools",
        //     "Toys, Kids & Baby",
        //     "Sports & Outdoors",
        //     "Automotive & Industrial",
        //     "Handmade",
        //     "Health & Household",
        //     "Car Parts & Accessories",
        //     "Arts, Crafts & Sewing",
        //     "Electronics & Computers",
        //     "Home & Kitchen",
        //     "Musical Instruments",
        //     "Industrial & Scientific",
        //     "Baby",
        //     "Appliances",
        //     "Personal Care & Beauty",
        //     "Office Products",
        //     "Software",
        //     "Movies & TV",
        //     "Video Games",
        //     "Collectibles & Fine Art",
        //     "CD & Vinyl",
        //     "Digital Music",
        //     "Gift Cards",
        //     "Grocery",
        //     "Pet Supplies & Products",
        //     "Amazon Devices",
        //     "Kindle Store",
        //     "Prime Video",
        //     "Pantries",
        //     "Gourmet",
        //     "Subscribe & Save",
        //     "Fashion",
        //     "Sunglasses",
        //     "Handbags",
        //     "Shirts",
        //     "Dresses",
        //     "Swimwear",
        //     "Jeans",
        //     "Sweaters",
        //     "Outerwear",
        //     "Underwear",
        //     "Socks",
        //     "Blazers",
        //     "Ties",
        //     "Watches",
        //     "Belts",
        //     "Hats",
        //     "Scarves",
        //     "Gloves",
        //     "Sleepwear",
        //     "Activewear",
        //     "Boots",
        //     "Heels",
        //     "Flats",
        //     "Sandals",
        //     "Sneakers",
        //     "Loafers",
        //     "Slippers",
        //     "Athletic Shoes",
        //     "Backpacks",
        //     "Shoulder Bags",
        //     "Tote Bags",
        //     "Clutches",
        //     "Messenger Bags",
        //     "Wallets",
        //     "Luggage",
        //     "Briefcases",
        //     "Beanies",
        //     "Earrings",
        //     "Necklaces",
        //     "Bracelets",
        //     "Rings",
        //     "Hair Accessories",
        //     "Sunglasses",
        //     "Watches",
        //     "Makeup",
        //     "Skin Care",
        //     "Hair Care",
        //     "Nail Care",
        //     "Bath & Body",
        //     "Fragrance",
        //     "Shaving & Grooming",
        //     "Personal Care",
        //     "Diet & Nutrition",
        //     "Supplements",
        //     "Weight Loss",
        //     "Exercise Equipment",
        //     "Fitness Accessories",
        //     "Kitchen Appliances",
        //     "Cookware",
        //     "Bakeware",
        //     "Small Appliances",
        //     "Home Organization",
        //     "Furniture",
        //     "Bedroom",
        //     "Living Room",
        //     "Dining Room",
        //     "Bathroom",
        //     "Office",
        //     "Lighting",
        //     "Wall Decor",
        //     "Home Accents",
        //     "Bedding",
        //     "Bath Accessories",
        //     "Towels",
        //     "Bed Pillows",
        //     "Bath Mats",
        //     "Electronics",
        //     "Televisions",
        //     "Audio Equipment",
        //     "Headphones",
        //     "Cameras",
        //     "Video Games",
        //     "Cell Phones",
        //     "Tablets",
        //     "Laptops",
        //     "Computer Accessories",
        //     "Printers",
        //     "Scanners",
        //     "Monitors",
        //     "Speakers",
        //     "Home Theater Systems",
        //     "Smart Home Devices",
        //     "Gaming Consoles",
        //     "Video Game Accessories",
        //     "Action Figures",
        //     "Dolls",
        //     "Building Sets",
        //     "Educational Toys",
        //     "Puzzles",
        //     "Board Games",
        //     "Outdoor Play",
        //     "Arts & Crafts",
        //     "Musical Instruments",
        //     "Exercise & Fitness",
        //     "Team Sports",
        //     "Outdoor Recreation",
        //     "Camping & Hiking",
        //     "Cycling",
        //     "Fishing",
        //     "Golf",
        //     "Water Sports",
        //     "Winter Sports",
        //     "Collectibles",
        //     "Decorative Collectibles",
        //     "Coins & Currency",
        //     "Fine Art",
        //     "Trading Cards",
        //     "Sports Memorabilia",
        //     "DVDs",
        //     "Blu-ray",
        //     "CDs",
        //     "Vinyl Records",
        //     "Digital Music",
        //     "Music Instruments",
        //     "Gift Cards",
        //     "Grocery",
        //     "Beverages",
        //     "Snacks",
        //     "Canned Goods",
        //     "Sauces & Dressings",
        //     "Pantry Staples",
        //     "Frozen Foods",
        //     "Bakery",
        //     "Desserts",
        //     "Coffee",
        //     "Tea",
        //     "Vitamins & Supplements",
        //     "Personal Care",
        //     "First Aid",
        //     "Health Monitors",
        //     "Mobility Aids",
        //     "Medicine Cabinet",
        //     "Home Tests",
        //     "Hand Tools",
        //     "Power Tools",
        //     "Hardware",
        //     "Garage Storage",
        //     "Appliances",
        //     "Lighting & Ceiling Fans",
        //     "Plumbing",
        //     "Electrical",
        //     "Painting Supplies",
        //     "Outdoor Power Equipment",
        //     "Gardening Tools",
        //     "Patio Furniture",
        //     "Grills",
        //     "Outdoor Decor",
        //     "Automotive Parts",
        //     "Accessories",
        //     "Motorcycle Parts",
        //     "Tools & Equipment",
        //     "Car Care",
        //     "Oils & Fluids",
        //     "Travel Accessories",
        //     "Luggage",
        //     "Travel Electronics",
        //     "Travel Clothing",
        //     "Travel Essentials",
        //     "Womens Clothing",
        //     "Mens Clothing",
        //     "Kids Clothing",
        //     "Shoes",
        //     "Accessories",
        //     "Home",
        //     "Kitchen & Dining",
        //     "Bedding & Bath",
        //     "Furniture",
        //     "Patio & Garden",
        //     "Electronics",
        //     "Books",
        //     "Movies, Music & Games",
        //     "Toys",
        //     "Baby",
        //     "Sports & Outdoors",
        //     "Automotive",
        //     "Health & Beauty",
        //     "Pet Supplies",
        //     "Arts & Entertainment",
        //     "Electronics",
        //     "Books & Media",
        //     "Automotive & Transportation",
        //     "Collectibles & Art",
        //     "Home & Garden",
        //     "Sporting Goods",
        //     "Toys & Games",
        //     "Baby & Kids",
        //     "Fashion & Accessories",
        //     "Fitness & Health",
        //     "Business & Industrial",
        //     "Travel & Luggage",
        //     "Movies & Music",
        //     "Gifts & Parties",
        //     "Food & Beverages",
        //     "Crafts & Hobbies",
        //     "Stationery & Office",
        //     "Digital Products",
        //     "Home Improvement & Tools",
        //     "Beauty & Personal Care",
        //     "Video Games & Consoles",
        //     "Jewelry & Watches",
        //     "Handmade Products",
        //     "Bathroom",
        //     "Bedroom",
        //     "Cleaning Supplies",
        //     "Furniture",
        //     "Home Decor",
        //     "Kitchen & Dining",
        //     "Gardening",
        //     "Outdoor Living",
        //     "Pets",
        //     "Smart Home & Appliances",
        //     "Baby & Toddler",
        //     "Toys & Games",
        //     "Learning & Education",
        //     "Clothing",
        //     "Shoes & Accessories",
        //     "Nursery",
        //     "Safety",
        //     "Car Seats",
        //     "Strollers",
        //     "Carriers & Slings"
        //   ]}');

        // foreach ($categories->categories as $category) {
        //     DB::table('placeholders')->insert([
        //         'type' => 'category',
        //         'value' => $category
        //     ]);
        // }



    }
}
